# Baseline ML models


In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# Reading datasets and creating test train split

In [2]:
data = pd.read_csv('dataset.csv',sep=',',names=['Msg','Tag'])
data1 = pd.read_csv('dataset_POS.csv',sep=',',names=['Msg','Tag'])
data2 = pd.read_csv('dataset_stemmed.csv',sep=',',names=['Msg','Tag'])

data.head()

Msg  Tag
0  The thing disgusting White woman groid White w...    1
1                Americans acting like know talking     0
2  Also intrested check webpage info european ame...    0
3  I think need take stand homes across country a...    0
4  I think connection homosexuality Christianity ...    1

In [3]:
data_x=data["Msg"]
data_y=data["Tag"]
cv = CountVectorizer()
x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, test_size=0.2, random_state=4)

data1_x=data1["Msg"]
data1_y=data1["Tag"]
cv = CountVectorizer()
x1_train, x1_test, y1_train, y1_test = train_test_split(data1_x, data1_y, test_size=0.2, random_state=4)

data2_x=data2["Msg"]
data2_y=data2["Tag"]
cv = CountVectorizer()
x2_train, x2_test, y2_train, y2_test = train_test_split(data2_x, data2_y, test_size=0.2, random_state=4)

x_train.head()

8752    Also stupid white women watch Oprah realize fa...
9141                     Jews insane literal demonic DNA 
5426                           I go I post soon possible 
2197    Hey live smithfield lived newport news jeffers...
8687    Manic street preachers also red scum basically...
Name: Msg, dtype: object

In [4]:
cv = CountVectorizer()
x_traincv = cv.fit_transform(["bayhdb hab ujhanvuz sniugnv","shnf nfuje test test","test anhf janbd whbj"])
x_traincv.toarray()
cv.get_feature_names()

['anhf',
 'bayhdb',
 'hab',
 'janbd',
 'nfuje',
 'shnf',
 'sniugnv',
 'test',
 'ujhanvuz',
 'whbj']

# Defining and fitting count vectorizer

In [5]:
cv1 = CountVectorizer()
x_traincv=cv1.fit_transform(x_train.values.astype('U'))
a=x_traincv.toarray()
a[0]

cv11 = CountVectorizer()
x1_traincv=cv11.fit_transform(x1_train.values.astype('U'))
a1=x1_traincv.toarray()
a1[0]

cv12 = CountVectorizer()
x2_traincv=cv12.fit_transform(x2_train.values.astype('U'))
a2=x2_traincv.toarray()
a2[0]

array([0, 0, 0, ..., 0, 0, 0])

In [6]:
x_testcv=cv1.transform(x_test.values.astype('U'))
x_testcv.toarray()

x1_testcv=cv11.transform(x1_test.values.astype('U'))
x1_testcv.toarray()

x2_testcv=cv12.transform(x2_test.values.astype('U'))
x2_testcv.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Naive Bayes classification model

In [13]:
mnb = MultinomialNB()
mnb1 = MultinomialNB()
mnb2 = MultinomialNB()

y_train=y_train.astype('int')
y_train

y1_train=y1_train.astype('int')
y1_train

y2_train=y2_train.astype('int')
y2_train

8752     0
9141     1
5426     0
2197     0
8687     1
        ..
6017     0
709      0
10679    0
8366     0
1146     0
Name: Tag, Length: 8755, dtype: int64

In [14]:
mnb.fit(x_traincv,y_train)
mnb1.fit(x1_traincv,y1_train)
mnb2.fit(x2_traincv,y2_train)



MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [22]:
predictions=mnb.predict(x_testcv)
print(predictions)
a=np.array(y_test)

predictions1=mnb1.predict(x1_testcv)
print(predictions1)
a1=np.array(y1_test)

predictions2=mnb2.predict(x2_testcv)
print(predictions2)
a2=np.array(y2_test)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


# Calculating accuracies of the model

In [16]:
count = 0
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1

count1 = 0
for i in range (len(predictions1)):
    if predictions1[i]==a1[i]:
        count1=count1+1

count2 = 0
for i in range (len(predictions2)):
    if predictions2[i]==a2[i]:
        count2=count2+1

In [19]:
print("Accuracy of Naive bayes with dataset")
print(count/len(predictions))
print("Accuracy of Naive bayes with POS tagged dataset")
print(count1/len(predictions1))
print("Accuracy of Naive bayes with stemmed and POS tagged dataset")
print(count2/len(predictions2))


Accuracy of Naive bayes with dataset
0.8780264961169484
Accuracy of Naive bayes with POS tagged dataset
0.8793969849246231
Accuracy of Naive bayes with stemmed and POS tagged dataset
0.8784833257195066
