# Baseline ML models


In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# Reading datasets and creating test train split

In [17]:
data = pd.read_csv('data_raw.csv',sep=',',names=['Msg','Tag'])
from collections import Counter
print(Counter(data['Tag']))
data.head()

Counter({1: 19190, 2: 4163, 0: 1430})


Msg  Tag
0   jaydillz my babies pussy is too tight today t...    1
1   seymourblanco they game is over fuck yall bit...    1
2     can you let me stretch that pussy out or nahhh    1
3  don t mind that twinkies are gonna be gone ver...    2
4  cnt nobody be mad at who he choose to be with ...    1

In [3]:
data_x=data["Msg"]
data_y=data["Tag"]
cv = CountVectorizer()
x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, test_size=0.2, random_state=4)

x_train.head()

13479    if ive ever been a faggot to you let me know a...
11021    if i straighten my hair it s gonna be long and...
6053     wanna find out the truth about somebody just t...
1310      darealalexinla woody afc rodriguez the nig is...
22170     andyydotcom you gotta be a weak bitch to let ...
Name: Msg, dtype: object

In [ ]:
cv = CountVectorizer()
x_traincv = cv.fit_transform(["bayhdb hab ujhanvuz sniugnv","shnf nfuje test test","test anhf janbd whbj"])
x_traincv.toarray()
cv.get_feature_names()

['anhf',
 'bayhdb',
 'hab',
 'janbd',
 'nfuje',
 'shnf',
 'sniugnv',
 'test',
 'ujhanvuz',
 'whbj']

# Defining and fitting count vectorizer

In [4]:
cv1 = CountVectorizer()
x_traincv=cv1.fit_transform(x_train.values.astype('U'))
a=x_traincv.toarray()
a[0]



array([0, 0, 0, ..., 0, 0, 0])

In [5]:
x_testcv=cv1.transform(x_test.values.astype('U'))
x_testcv.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# 1) Naive Bayes classification model

In [6]:
mnb = MultinomialNB()
y_train=y_train.astype('int')
y_train


13479    1
11021    1
6053     1
1310     0
22170    1
        ..
11863    1
22401    1
17093    2
8366     2
17530    2
Name: Tag, Length: 19826, dtype: int64

In [7]:
mnb.fit(x_traincv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [8]:
predictions=mnb.predict(x_testcv)
print(predictions)
a=np.array(y_test)


[1 2 1 ... 2 1 1]


# Calculating accuracies of the Naive Bayes model


In [9]:
count = 0
for i in range (len(predictions)):
    if predictions[i]==a[i]:

In [10]:
print("Accuracy of Naive bayes with dataset")
print(count/len(predictions))

print(" ")
print("F1 score of Naive bayes with dataset")
print(f1_score(a, predictions, average='macro'))

print(" ")
print("Precision score of Naive bayes with dataset")
print(precision_score(a, predictions, average='macro'))

print(" ")
print("Recall score of Naive bayes with dataset")
print(recall_score(a, predictions, average='macro'))


Accuracy of Naive bayes with dataset
0.8603994351422232
 
F1 score of Naive bayes with dataset
0.5482510676369398
 
Precision score of Naive bayes with dataset
0.7509347463150283
 
Recall score of Naive bayes with dataset
0.5180319416818895


# 2) SVM classification model

In [11]:
svm = make_pipeline(StandardScaler(with_mean=False), SVC(gamma='auto'))

svm.fit(x_traincv,y_train)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=False, with_std=True)),
                ('svc',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', degree=3,
                     gamma='auto', kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)

In [12]:
predictions=svm.predict(x_testcv)
print(predictions)
a=np.array(y_test)


[1 1 1 ... 1 1 1]


In [13]:
count = 0
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1


In [14]:
print("Accuracy of SVM with dataset")
print(count/len(predictions))

print(" ")
print("F1 of SVM with dataset")
print(f1_score(a, predictions, average='macro'))

print(" ")
print("Precision score of SVM with dataset")
print(precision_score(a, predictions, average='macro'))

print(" ")
print("Recall score of SVM with dataset")
print(recall_score(a, predictions, average='macro'))


Accuracy of SVM with dataset
0.7803106717772846
 
Accuracy of SVM with dataset
0.3125183749477444
 
Precision score of SVM with dataset
0.5702054594785011
 
Recall score of SVM with dataset
0.3437114855240921


# 3) Logistic regression Classification model

In [30]:
lr = LogisticRegression(random_state=0, solver='lbfgs',multi_class='multinomial')

lr.fit(x_traincv,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
predictions=lr.predict(x_testcv)
print(predictions)
a=np.array(y_test)

[1 1 1 ... 2 1 1]


In [32]:
count = 0
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1

In [33]:
print("Accuracy of LR with dataset")
print(count/len(predictions))
print(" ")
print("F1 of LR with dataset")
print(f1_score(a, predictions, average='macro'))
print(" ")
print("Precision score of LR with dataset")
print(precision_score(a, predictions, average='macro'))
print(" ")
print("Recall score of LR with dataset")
print(recall_score(a, predictions, average='macro'))

Accuracy of LR with dataset
0.9039741779301997
 
Accuracy of LR with dataset
0.6996201138114778
 
Precision score of LR with dataset
0.7351294308699409
 
Recall score of LR with dataset
0.6874121382669932


# 4) Decision Trees Classification model

In [22]:
dt = tree.DecisionTreeClassifier()

dt.fit(x_traincv,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [23]:
predictions=dt.predict(x_testcv)
print(predictions)
a=np.array(y_test)

[1 1 1 ... 2 1 1]


In [24]:
count = 0
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1


In [25]:
print("Accuracy of decision trees with dataset")
print(count/len(predictions))
print(" ")
print("F1 of decision trees with dataset")
print(f1_score(a, predictions, average='macro'))
print(" ")
print("Precision score of decision trees with dataset")
print(precision_score(a, predictions, average='macro'))
print(" ")
print("Recall score of decision trees with dataset")
print(recall_score(a, predictions, average='macro'))

Accuracy of decision trees with dataset
0.8846076255799878
 
Accuracy of decision trees with dataset
0.6731380158555137
 
Precision score of decision trees with dataset
0.680101552296828
 
Recall score of decision trees with dataset
0.668332123277354
